#!/usr/bin/env bash
set -euo pipefail
ROOT="${AGY_SANDBOX_ROOT:-$HOME/agy-sandbox}"; SANDBOX=""; PROMPT_FILE=""; MODE=""; AGENT=""
while [[ $# -gt 0 ]]; do case "$1" in --sandbox) SANDBOX="$2"; shift 2 ;; --prompt-file) PROMPT_FILE="$2"; shift 2 ;; --mode) MODE="$2"; shift 2 ;; --agent) AGENT="$2"; shift 2 ;; *) echo "Unknown argument: $1" >&2; exit 2 ;; esac; done
[[ -n "$SANDBOX" && -n "$PROMPT_FILE" ]] || { echo "Usage: --sandbox <dir> --prompt-file <file> [--mode plan|accept-edits] [--agent <name>]" >&2; exit 2; }
VIEWER_HELPER="${AGY_LIVE_VIEWER_HELPER:-$HOME/.codex/skills/antigravity-sandbox/scripts/ensure-live-viewer.sh}"
[[ -x "$VIEWER_HELPER" ]] || { echo "AGY Live Inspector helper is missing or not executable: $VIEWER_HELPER" >&2; exit 2; }
"$VIEWER_HELPER"
ROOT="$(cd "$ROOT" && pwd -P)"; SANDBOX="$(cd "$SANDBOX" && pwd -P)"; PROMPT_FILE="$(cd "$(dirname "$PROMPT_FILE")" && pwd -P)/$(basename "$PROMPT_FILE")"
case "$SANDBOX" in "$ROOT"/*) ;; *) echo "Sandbox must be inside $ROOT" >&2; exit 2 ;; esac; case "$PROMPT_FILE" in "$SANDBOX"/*) ;; *) echo "Prompt file must be inside the sandbox" >&2; exit 2 ;; esac
[[ -f "$PROMPT_FILE" ]] || { echo "Prompt file not found" >&2; exit 2; }; [[ -z "$MODE" || "$MODE" == "plan" || "$MODE" == "accept-edits" ]] || { echo "Mode must be plan or accept-edits" >&2; exit 2; }
LOG="$SANDBOX/agy.log"; MANIFEST="$SANDBOX/.agy-viewer-run.json"; PROMPT_COPY="$SANDBOX/.agy-prompt.md"; cp "$PROMPT_FILE" "$PROMPT_COPY"
write_manifest() { local status="$1" ended="${2:-}" code="${3:-}" termination="${4:-}"; AGY_STATUS="$status" AGY_ENDED="$ended" AGY_CODE="$code" AGY_TERMINATION="$termination" AGY_PID="$PID" AGY_PGID="$PGID" AGY_STARTED="$STARTED" AGY_SANDBOX="$SANDBOX" AGY_PROMPT="$PROMPT_COPY" AGY_MODE="$MODE" AGY_AGENT="$AGENT" node -e 'const fs=require("fs");const e=process.env;const d={version:1,status:e.AGY_STATUS,sandboxPath:e.AGY_SANDBOX,prompt:fs.readFileSync(e.AGY_PROMPT,"utf8"),startedAt:e.AGY_STARTED,pid:Number(e.AGY_PID),pgid:Number(e.AGY_PGID),mode:e.AGY_MODE||null,agent:e.AGY_AGENT||null};if(e.AGY_ENDED)d.endedAt=e.AGY_ENDED;if(e.AGY_CODE!=="")d.exitCode=Number(e.AGY_CODE);if(e.AGY_TERMINATION)d.termination=e.AGY_TERMINATION;fs.writeFileSync(process.argv[1],JSON.stringify(d,null,2)+"\n")' "$MANIFEST"; }
cd "$SANDBOX"; STARTED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"; : > "$LOG"; ARGS=(--add-dir "$SANDBOX" --print "$(cat "$PROMPT_COPY")"); [[ -n "$MODE" ]] && ARGS=(--mode "$MODE" "${ARGS[@]}"); [[ -n "$AGENT" ]] && ARGS=(--agent "$AGENT" "${ARGS[@]}"); agy "${ARGS[@]}" > "$LOG" 2>&1 & PID=$!; PGID="$(ps -o pgid= -p "$PID" | tr -d ' ')"; write_manifest running
deadline=$((SECONDS + 360)); last_size=-1; last_change=$SECONDS; termination=""; while kill -0 "$PID" 2>/dev/null; do size="$(wc -c < "$LOG" | tr -d ' ')"; [[ "$size" != "$last_size" ]] && { last_size="$size"; last_change=$SECONDS; }; [[ "$SECONDS" -ge "$deadline" ]] && { termination="timeout-6min"; break; }; [[ $((SECONDS-last_change)) -ge 90 ]] && { termination="stall-90s-no-output"; break; }; sleep 5; done
if [[ -n "$termination" ]]; then kill -TERM -"$PGID" 2>/dev/null || true; sleep 5; kill -KILL -"$PGID" 2>/dev/null || true; fi; set +e; wait "$PID"; code=$?; set -e; ended="$(date -u +%Y-%m-%dT%H:%M:%SZ)"; status="completed"; [[ -n "$termination" ]] && status="stalled"; [[ "$code" -ne 0 && -z "$termination" ]] && status="failed"; write_manifest "$status" "$ended" "$code" "$termination"; printf 'status=%s exit=%s termination=%s\n' "$status" "$code" "$termination"; exit "$code"
